# AlpineLinux with a glibc-2.27-r0 And Oracle Java 8
FROM casstime/alpine-glibc-server-jre-8:base
MAINTAINER Jim Xu <jian.xu@casstime.com>


RUN apk add python && \
    python --version && \
    \
    echo "安装python成功~"
